
import React from "react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import PageLayout from "@/components/layout/PageLayout";
import { Code, Rocket, Sparkles, Zap, Users, FileText, CheckCircle } from "lucide-react";

const Index = () => {
  return (
    <PageLayout>
      {/* Hero Section */}
      <section className="relative py-20">
        <div className="absolute inset-0 bg-gradient-to-br from-vibe-purple/10 via-vibe-blue/10 to-vibe-pink/10 pointer-events-none" />
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center space-y-8 text-center">
            <div className="space-y-2">
              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl lg:text-7xl">
                Bringing the <span className="text-gradient font-extrabold">Vibes</span> to Your Coding Journey
              </h1>
              <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl">
                AI-powered learning, resources, and a vibrant community to elevate your development skills
              </p>
            </div>
            <div className="flex flex-wrap gap-4 justify-center">
              <Link to="/learn">
                <Button size="lg" className="bg-primary hover:bg-primary/90">
                  Start Learning
                  <Rocket className="ml-2 h-5 w-5" />
                </Button>
              </Link>
              <Link to="/marketplace">
                <Button size="lg" variant="outline">
                  Explore Marketplace
                  <Sparkles className="ml-2 h-5 w-5" />
                </Button>
              </Link>
            </div>
            <div className="relative w-full max-w-4xl aspect-video rounded-lg overflow-hidden border">
              <div className="absolute inset-0 flex items-center justify-center bg-black/10 backdrop-blur-sm">
                <div className="w-16 h-16 rounded-full bg-white/80 flex items-center justify-center">
                  <div className="w-12 h-12 rounded-full bg-primary flex items-center justify-center">
                    <svg className="w-6 h-6 text-white" fill="currentColor" viewBox="0 0 24 24">
                      <path d="M8 5v14l11-7z" />
                    </svg>
                  </div>
                </div>
              </div>
              <div className="absolute inset-0 bg-gradient-to-t from-background via-transparent to-transparent opacity-70" />
              <div className="absolute bottom-4 left-4 right-4 text-left">
                <h3 className="text-xl font-semibold text-white shadow-sm">Discover VybeCoding</h3>
                <p className="text-sm text-white/80 shadow-sm">Watch our introduction to learn about all our features</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 bg-muted/30">
        <div className="container px-4 md:px-6">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Powered by <span className="text-gradient">AI</span>, Built for You
            </h2>
            <p className="mx-auto max-w-[700px] mt-4 text-muted-foreground">
              Discover how VybeCoding combines cutting-edge AI with modern web development practices
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {/* Feature Card 1 */}
            <Card className="backdrop-blur-md bg-background/50">
              <CardHeader className="pb-2">
                <div className="w-12 h-12 rounded-lg bg-gradient-to-br from-vibe-purple to-vibe-blue flex items-center justify-center">
                  <Code className="text-white h-6 w-6" />
                </div>
                <CardTitle className="mt-4">AI-Powered Learning</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground">
                  Personalized tutorials and learning paths generated by AI based on your skill level and interests.
                </p>
              </CardContent>
              <CardFooter>
                <Link to="/learn">
                  <Button variant="ghost" size="sm" className="gap-1">
                    Learn more <Zap className="h-4 w-4" />
                  </Button>
                </Link>
              </CardFooter>
            </Card>

            {/* Feature Card 2 */}
            <Card className="backdrop-blur-md bg-background/50">
              <CardHeader className="pb-2">
                <div className="w-12 h-12 rounded-lg bg-gradient-to-br from-vibe-blue to-vibe-pink flex items-center justify-center">
                  <Sparkles className="text-white h-6 w-6" />
                </div>
                <CardTitle className="mt-4">Marketplace</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground">
                  Discover and purchase premium templates, components, and courses created by our community of developers.
                </p>
              </CardContent>
              <CardFooter>
                <Link to="/marketplace">
                  <Button variant="ghost" size="sm" className="gap-1">
                    Explore marketplace <Zap className="h-4 w-4" />
                  </Button>
                </Link>
              </CardFooter>
            </Card>

            {/* Feature Card 3 */}
            <Card className="backdrop-blur-md bg-background/50">
              <CardHeader className="pb-2">
                <div className="w-12 h-12 rounded-lg bg-gradient-to-br from-vibe-pink to-vibe-purple flex items-center justify-center">
                  <Users className="text-white h-6 w-6" />
                </div>
                <CardTitle className="mt-4">Community Forum</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground">
                  Connect with other developers, share your work, and get help with your coding challenges.
                </p>
              </CardContent>
              <CardFooter>
                <Link to="/forum">
                  <Button variant="ghost" size="sm" className="gap-1">
                    Join community <Zap className="h-4 w-4" />
                  </Button>
                </Link>
              </CardFooter>
            </Card>
          </div>
        </div>
      </section>

      {/* AI Blog Preview Section */}
      <section className="py-16">
        <div className="container px-4 md:px-6">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
              Latest from the <span className="text-gradient">AI-Powered Blog</span>
            </h2>
            <p className="mx-auto max-w-[700px] mt-4 text-muted-foreground">
              Automatically generated content about the latest trends in web development and AI
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {/* Blog Card 1 */}
            <Card>
              <CardHeader>
                <div className="h-40 rounded-lg bg-muted overflow-hidden mb-4">
                  <div className="w-full h-full bg-gradient-to-br from-vibe-purple/20 via-vibe-blue/20 to-vibe-pink/20 flex items-center justify-center">
                    <FileText className="h-10 w-10 text-muted-foreground" />
                  </div>
                </div>
                <CardTitle className="line-clamp-2">The Rise of AI-Powered Development Tools</CardTitle>
                <CardDescription>Feb 28, 2024 • 5 min read</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground line-clamp-3">
                  Explore how AI is transforming the way developers write code, debug applications, and design user interfaces...
                </p>
              </CardContent>
              <CardFooter>
                <Link to="/blog/ai-development-tools">
                  <Button variant="ghost" size="sm">Read article</Button>
                </Link>
              </CardFooter>
            </Card>

            {/* Blog Card 2 */}
            <Card>
              <CardHeader>
                <div className="h-40 rounded-lg bg-muted overflow-hidden mb-4">
                  <div className="w-full h-full bg-gradient-to-br from-vibe-blue/20 via-vibe-pink/20 to-vibe-purple/20 flex items-center justify-center">
                    <FileText className="h-10 w-10 text-muted-foreground" />
                  </div>
                </div>
                <CardTitle className="line-clamp-2">Building Responsive UIs with React and Tailwind</CardTitle>
                <CardDescription>Feb 25, 2024 • 7 min read</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground line-clamp-3">
                  Learn how to combine the power of React with the utility-first approach of Tailwind CSS to build beautiful, responsive interfaces...
                </p>
              </CardContent>
              <CardFooter>
                <Link to="/blog/react-tailwind-ui">
                  <Button variant="ghost" size="sm">Read article</Button>
                </Link>
              </CardFooter>
            </Card>

            {/* Blog Card 3 */}
            <Card>
              <CardHeader>
                <div className="h-40 rounded-lg bg-muted overflow-hidden mb-4">
                  <div className="w-full h-full bg-gradient-to-br from-vibe-pink/20 via-vibe-purple/20 to-vibe-blue/20 flex items-center justify-center">
                    <FileText className="h-10 w-10 text-muted-foreground" />
                  </div>
                </div>
                <CardTitle className="line-clamp-2">The Future of Web Development: What's Next?</CardTitle>
                <CardDescription>Feb 20, 2024 • 6 min read</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground line-clamp-3">
                  From WebAssembly to Edge Computing, discover the emerging technologies that are shaping the future of web development...
                </p>
              </CardContent>
              <CardFooter>
                <Link to="/blog/future-web-dev">
                  <Button variant="ghost" size="sm">Read article</Button>
                </Link>
              </CardFooter>
            </Card>
          </div>

          <div className="flex justify-center mt-8">
            <Link to="/blog">
              <Button variant="outline">View all articles</Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Learning Paths Section */}
      <section className="py-16 bg-muted/30">
        <div className="container px-4 md:px-6">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
              Personalized <span className="text-gradient">Learning Paths</span>
            </h2>
            <p className="mx-auto max-w-[700px] mt-4 text-muted-foreground">
              Choose your journey and let our AI create a customized learning experience for you
            </p>
          </div>

          <Tabs defaultValue="frontend" className="max-w-3xl mx-auto">
            <TabsList className="grid w-full grid-cols-3 mb-8">
              <TabsTrigger value="frontend">Frontend</TabsTrigger>
              <TabsTrigger value="backend">Backend</TabsTrigger>
              <TabsTrigger value="fullstack">Full Stack</TabsTrigger>
            </TabsList>
            <TabsContent value="frontend" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle>Frontend Development Path</CardTitle>
                  <CardDescription>Master modern UI development with React, Next.js, and more</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex items-start gap-4">
                    <CheckCircle className="h-5 w-5 text-vibe-green mt-0.5" />
                    <div>
                      <h4 className="font-medium">HTML, CSS & JavaScript Fundamentals</h4>
                      <p className="text-sm text-muted-foreground">Build a solid foundation with the core web technologies</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <CheckCircle className="h-5 w-5 text-vibe-green mt-0.5" />
                    <div>
                      <h4 className="font-medium">Modern React Development</h4>
                      <p className="text-sm text-muted-foreground">Learn hooks, context, and modern React patterns</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <CheckCircle className="h-5 w-5 text-vibe-green mt-0.5" />
                    <div>
                      <h4 className="font-medium">Styling & UI Libraries</h4>
                      <p className="text-sm text-muted-foreground">Master Tailwind CSS, shadcn/ui, and component design</p>
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <Link to="/learn/frontend">
                    <Button>Start Frontend Path</Button>
                  </Link>
                </CardFooter>
              </Card>
            </TabsContent>
            <TabsContent value="backend" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle>Backend Development Path</CardTitle>
                  <CardDescription>Build robust server-side applications and APIs</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex items-start gap-4">
                    <CheckCircle className="h-5 w-5 text-vibe-green mt-0.5" />
                    <div>
                      <h4 className="font-medium">Node.js Fundamentals</h4>
                      <p className="text-sm text-muted-foreground">Learn server-side JavaScript with Express and NestJS</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <CheckCircle className="h-5 w-5 text-vibe-green mt-0.5" />
                    <div>
                      <h4 className="font-medium">Database Design & ORM</h4>
                      <p className="text-sm text-muted-foreground">Work with SQL, NoSQL, and Prisma for data management</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <CheckCircle className="h-5 w-5 text-vibe-green mt-0.5" />
                    <div>
                      <h4 className="font-medium">API Development</h4>
                      <p className="text-sm text-muted-foreground">Design and implement RESTful and GraphQL APIs</p>
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <Link to="/learn/backend">
                    <Button>Start Backend Path</Button>
                  </Link>
                </CardFooter>
              </Card>
            </TabsContent>
            <TabsContent value="fullstack" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle>Full Stack Development Path</CardTitle>
                  <CardDescription>Become a versatile developer capable of building end-to-end applications</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="flex items-start gap-4">
                    <CheckCircle className="h-5 w-5 text-vibe-green mt-0.5" />
                    <div>
                      <h4 className="font-medium">Frontend & Backend Fundamentals</h4>
                      <p className="text-sm text-muted-foreground">Master both client and server-side development</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <CheckCircle className="h-5 w-5 text-vibe-green mt-0.5" />
                    <div>
                      <h4 className="font-medium">Next.js & Full Stack Frameworks</h4>
                      <p className="text-sm text-muted-foreground">Build applications with modern full stack frameworks</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-4">
                    <CheckCircle className="h-5 w-5 text-vibe-green mt-0.5" />
                    <div>
                      <h4 className="font-medium">Deployment & DevOps</h4>
                      <p className="text-sm text-muted-foreground">Learn CI/CD, containerization, and cloud deployment</p>
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <Link to="/learn/fullstack">
                    <Button>Start Full Stack Path</Button>
                  </Link>
                </CardFooter>
              </Card>
            </TabsContent>
          </Tabs>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-vibe-purple/20 via-vibe-blue/20 to-vibe-pink/20" />
        <div className="container px-4 md:px-6 relative z-10">
          <div className="max-w-3xl mx-auto text-center space-y-8">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
              Ready to Start Your <span className="text-gradient">Coding Journey</span>?
            </h2>
            <p className="text-muted-foreground text-lg">
              Join thousands of developers who have already leveled up their skills with VybeCoding
            </p>
            <div className="flex flex-wrap gap-4 justify-center">
              <Link to="/signup">
                <Button size="lg" className="bg-primary hover:bg-primary/90">
                  Sign Up Now
                  <Sparkles className="ml-2 h-5 w-5" />
                </Button>
              </Link>
              <Link to="/learn">
                <Button size="lg" variant="outline">
                  Explore Free Lessons
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>
    </PageLayout>
  );
};

export default Index;
